In [89]:
import numpy as np
import torch

## 1D Array (Numpy)

In [90]:
t = np.array([0.,1.,2.,3.,4.,5.,6.]) #float
print(t,'\n')

print('Rank  of t : ',t.ndim)
print('Shape of t : ',t.shape,'\n')

print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])
print('t[:2] t[3:]     = ', t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.] 

Rank  of t :  1
Shape of t :  (7,) 

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 2D Array

In [91]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t,'\n')

print('Rank  of t : ',t.ndim)
print('Shape of t : ',t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] 

Rank  of t :  2
Shape of t :  (4, 3)


## 1D Array (PyTorch)

In [92]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t,'\n')

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.]) 

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array

In [93]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t,'\n')

print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Shape, Rank, Axis

In [94]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

print(t.dim())  #rank
print(t.size()) #shape

4
torch.Size([1, 2, 3, 4])


In [95]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2)) #행렬곱

m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2)) #각자 그냥 곱함 


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [96]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [97]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)


tensor([[4., 5.]])


In [98]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## mean

In [99]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [100]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [101]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [102]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## sum

In [103]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t,'\n')

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]]) 

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max, Argmax

In [104]:
t = torch.FloatTensor([[1, 3], [2, 4]])
print(t,'\n')

print(t.max(),'\n')

print(t.max(dim=0))
print('Max:', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1],'\n')

print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 3.],
        [2., 4.]]) 

tensor(4.) 

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
Max: tensor([2., 4.])
Argmax: tensor([1, 1]) 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


## View

In [105]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape,'\n')

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape,'\n')

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3]) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [106]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape,'\n')

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1]) 

tensor([0., 1., 2.])
torch.Size([3])


In [107]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape,'\n')

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape,'\n')

print(ft.view(1, -1))
print(ft.view(1, -1).shape,'\n')

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape,'\n')

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

torch.Size([3]) 

tensor([[0., 1., 2.]])
torch.Size([1, 3]) 

tensor([[0., 1., 2.]])
torch.Size([1, 3]) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1]) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Scatter

In [108]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt,'\n')

one_hot = torch.zeros(5, 4) #최소 숫자만 맞춰주면 됨
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[0],
        [1],
        [2],
        [0]]) 

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Casting

In [109]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [110]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenation

In [111]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [112]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=1))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4., 2., 5., 3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros Like

In [113]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))


tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [114]:
x = torch.FloatTensor([[1,2], [3,4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Zip

In [115]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

print('\n')
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6


1 4 7
2 5 8
3 6 9
